export const Details = [
  {
    id: 1,
    name: "Ameen",
    age: 22,
    gender: "Male",
    email: "ameen@gmail.com",
    phone: "9876543210",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
  },
  {
    id: 2,
    name: "Ravi",
    age: 24,
    gender: "Male",
    email: "ravi@gmail.com",
    phone: "9123456780",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    country: "India",

  },
  {
    id: 3,
    name: "Priya",
    age: 21,
    gender: "Female",
    email: "priya@gmail.com",
    phone: "9988776655",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",

  },
  {
    id: 4,
    name: "John",
    age: 25,
    gender: "Male",
    email: "john@gmail.com",
    phone: "9876501234",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
  },
  {
    id: 5,
    name: "Sneha",
    age: 23,
    gender: "Female",
    email: "sneha@gmail.com",
    phone: "9845671230",
    city: "Pune",
    state: "Maharashtra",
    country: "India",

  },
  {
    id: 6,
    name: "Arjun",
    age: 26,
    gender: "Male",
    email: "arjun@gmail.com",
    phone: "9765432108",
    city: "Kochi",
    state: "Kerala",
    country: "India",

  },
  {
    id: 7,
    name: "Neha",
    age: 24,
    gender: "Female",
    email: "neha@gmail.com",
    phone: "9654321078",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India"
  }
];